### ISSUE TITLE
R dependency

### ISSUE THREAD

**Issue by kvittingseerup** [Mporse/cellex.analysis#1]
You seem to have made the R dependency `3.50` instead of `3.5.0` meaning we acutally need `4.0.0` or higher to run it :-)

Also if you dont want us to have access to the helper function you can just modify the NAMESPACE file so the helper functions are not exported.

Cheers
Kristoffer

**Comment by Mporse** [comment]
Hi Kristoffer,

Thanks for pointing it out - should be fixed now :)

- Mads

**Comment by madsporse** [comment]
Hi Kristoffer,

Thanks for pointing it out - should be fixed now :)

\- Mads
